"use client";
import { motion, Variants } from "motion/react";
import Link from "next/link";
import {
  Lightbulb,
  TrendingUp,
  Zap,
  Target,
  ArrowRight,
  Sparkles,
  Users,
  Clock,
} from "lucide-react";
import { oswald } from "../ui/fonts";
import SignInGoogle from "../auth/SignInGoogle";
import Logo from "@/components/home/Logo";

const HomeNoUser = () => {
  const features = [
    {
      icon: Lightbulb,
      title: "AI-Powered Ideas",
      description:
        "Get viral LinkedIn post ideas generated by advanced AI that understands current trends and engagement patterns.",
    },
    {
      icon: TrendingUp,
      title: "Viral Optimization",
      description:
        "Every post is scored and optimized for maximum engagement with proven viral content strategies.",
    },
    {
      icon: Zap,
      title: "Instant Generation",
      description:
        "Create professional LinkedIn posts in seconds with our streamlined AI workflow and smart templates.",
    },
    {
      icon: Target,
      title: "Audience Targeting",
      description:
        "Content tailored for your specific professional audience to maximize relevance and impact.",
    },
  ];

  const benefits = [
    {
      icon: Sparkles,
      title: "10x Your Engagement",
      description: "Proven strategies that boost likes, comments, and shares",
    },
    {
      icon: Users,
      title: "Grow Your Network",
      description: "Connect with industry leaders and expand your reach",
    },
    {
      icon: Clock,
      title: "Save Hours Weekly",
      description: "Create compelling content in minutes, not hours",
    },
  ];

  const containerVariants: Variants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        duration: 0.6,
        staggerChildren: 0.1,
      },
    },
  };

  const itemVariants: Variants = {
    hidden: { opacity: 0, y: 20 },
    visible: {
      opacity: 1,
      y: 0,
      transition: {
        duration: 0.5,
        ease: [0.25, 0.46, 0.45, 0.94],
      },
    },
  };

  const iconVariants: Variants = {
    hidden: { opacity: 0, scale: 0.8 },
    visible: {
      opacity: 1,
      scale: 1,
      transition: {
        duration: 0.4,
        ease: [0.25, 0.46, 0.45, 0.94],
      },
    },
    hover: {
      scale: 1.1,
      rotate: 5,
      transition: {
        type: "spring",
        stiffness: 400,
        damping: 17,
      },
    },
  };

  return (
    <motion.div
      className="min-h-screen bg-gradient-to-br max-w-[1440px] mx-auto"
      variants={containerVariants}
      initial="hidden"
      animate="visible"
    >
      {/* Hero Section */}
      <motion.section
        className="text-center py-16 px-4"
        variants={itemVariants}
      >
        <div className="flex justify-center mb-8">
          <Logo />
        </div>

        <motion.h1
          className={`${oswald.className} text-5xl md:text-6xl lg:text-7xl font-bold text-slate-800 mb-6 tracking-wide`}
          variants={itemVariants}
        >
          TrendForge
        </motion.h1>

        <motion.div
          className="w-24 h-1 bg-gradient-to-r from-sky-400 to-blue-500 mx-auto rounded-full mb-8"
          variants={itemVariants}
        />

        <motion.p
          className="text-xl md:text-2xl text-slate-600 max-w-4xl mx-auto leading-relaxed mb-12"
          variants={itemVariants}
        >
          Create viral LinkedIn content with AI-powered precision. Generate
          engaging posts, discover trending topics, and grow your professional
          presence in minutes, not hours.
        </motion.p>

        <motion.div
          className="flex flex-col items-center gap-6 mb-16"
          variants={itemVariants}
        >
          <motion.div
            className="flex flex-col sm:flex-row gap-4 items-center"
            variants={itemVariants}
          >
            <SignInGoogle />
            <span className="text-slate-500 text-sm">Free to get started</span>
          </motion.div>

          <motion.p
            className="text-sm text-slate-500 max-w-md"
            variants={itemVariants}
          >
            Join thousands of professionals growing their LinkedIn presence with
            AI
          </motion.p>
        </motion.div>
      </motion.section>

      {/* Benefits Section */}
      <motion.section
        className="py-16 px-4 bg-white/50 backdrop-blur-sm"
        variants={itemVariants}
      >
        <motion.h2
          className={`${oswald.className} text-3xl md:text-4xl font-bold text-center text-slate-800 mb-12`}
          variants={itemVariants}
        >
          Transform Your LinkedIn Strategy
        </motion.h2>

        <div className="max-w-6xl mx-auto grid md:grid-cols-3 gap-8">
          {benefits.map((benefit, index) => (
            <motion.div
              key={index}
              className="text-center"
              variants={itemVariants}
              whileHover={{ y: -5 }}
              transition={{ type: "spring", stiffness: 400, damping: 17 }}
            >
              <motion.div
                className="flex items-center justify-center w-16 h-16 bg-gradient-to-br from-blue-600 to-sky-500 text-white rounded-full mx-auto mb-6 shadow-lg"
                variants={iconVariants}
                whileHover="hover"
              >
                <benefit.icon className="w-8 h-8" />
              </motion.div>
              <h3
                className={`${oswald.className} text-xl font-semibold text-slate-800 mb-4`}
              >
                {benefit.title}
              </h3>
              <p className="text-slate-600 leading-relaxed">
                {benefit.description}
              </p>
            </motion.div>
          ))}
        </div>
      </motion.section>

      {/* Features Section */}
      <motion.section className="py-16 px-4" variants={itemVariants}>
        <motion.h2
          className={`${oswald.className} text-3xl md:text-4xl font-bold text-center text-slate-800 mb-4`}
          variants={itemVariants}
        >
          Powerful AI Features
        </motion.h2>

        <motion.p
          className="text-lg text-slate-600 text-center max-w-2xl mx-auto mb-12"
          variants={itemVariants}
        >
          Everything you need to create compelling LinkedIn content that drives
          real engagement and grows your professional network.
        </motion.p>

        <div className="max-w-6xl mx-auto grid md:grid-cols-2 gap-8">
          {features.map((feature, index) => (
            <motion.div
              key={index}
              className="bg-white/70 backdrop-blur-sm p-8 rounded-xl shadow-sm border border-slate-200 hover:shadow-md hover:border-slate-300 transition-all duration-300"
              variants={itemVariants}
              whileHover={{ y: -5, scale: 1.02 }}
              transition={{ type: "spring", stiffness: 400, damping: 17 }}
            >
              <motion.div
                className="flex items-center mb-4"
                variants={iconVariants}
                whileHover="hover"
              >
                <div className="flex items-center justify-center w-12 h-12 bg-gradient-to-br from-blue-100 to-sky-100 rounded-lg mr-4">
                  <feature.icon className="w-6 h-6 text-blue-600" />
                </div>
                <h3
                  className={`${oswald.className} text-xl font-semibold text-slate-800`}
                >
                  {feature.title}
                </h3>
              </motion.div>
              <p className="text-slate-600 leading-relaxed">
                {feature.description}
              </p>
            </motion.div>
          ))}
        </div>
      </motion.section>

      {/* CTA Section */}
      <motion.section
        className="text-center py-16 px-4 bg-gradient-to-br from-slate-50 to-sky-50"
        variants={itemVariants}
      >
        <motion.h2
          className={`${oswald.className} text-4xl md:text-5xl font-bold text-slate-800 mb-6`}
          variants={itemVariants}
        >
          Ready to Go Viral?
        </motion.h2>

        <motion.p
          className="text-xl text-slate-600 max-w-3xl mx-auto mb-12 leading-relaxed"
          variants={itemVariants}
        >
          Start creating AI-powered LinkedIn content that gets noticed, drives
          engagement, and grows your professional influence. No credit card
          required.
        </motion.p>

        <motion.div
          className="flex flex-col items-center gap-6"
          variants={itemVariants}
        >
          <motion.div
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            transition={{ type: "spring", stiffness: 400, damping: 17 }}
          >
            <SignInGoogle />
          </motion.div>

          <motion.p className="text-sm text-slate-500" variants={itemVariants}>
            Get started in less than 30 seconds
          </motion.p>

          <motion.div
            className="flex flex-col sm:flex-row gap-4 mt-8"
            variants={itemVariants}
          >
            <motion.div
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
              transition={{ type: "spring", stiffness: 400, damping: 17 }}
            >
              <Link
                href="/about"
                className="inline-flex items-center gap-2 px-6 py-3 bg-white text-slate-700 border-2 border-slate-200 rounded-lg hover:bg-slate-50 hover:border-slate-300 transition-colors duration-200 font-medium"
              >
                Learn More
                <ArrowRight className="w-4 h-4" />
              </Link>
            </motion.div>
          </motion.div>
        </motion.div>
      </motion.section>
    </motion.div>
  );
};

export default HomeNoUser;
